added method substring($string, $after, $before) with tests
JonasRudolph/php-component-stringutility pull request #1
Opened 2017-02-01 21:45 UTC by stevleibelt

2017-02-02 14:49 UTC, JonasRudolph commented
Hey Stev,

vielen Dank für die Erweiterung! Ich hab noch nie ein Review für einen Pull Request gemacht, deswegen hoffe ich, dass ich nichts falsch mache/sage. 
Ich werde bei 'Files changed' ein paar Kommentare eingetragen. Ich hoffe davon ist keins unfreundlich oder so. Ist es okay, die Konversation/Kommentare in der Landessprache zu betreiben oder besser, sich hier trotzdem auf englisch zu unterhalten?

Liebe Grüße

Jonas

2017-02-02 15:08 UTC, JonasTaulien requested changes
Vielen dank :)

2017-02-02 15:08 UTC, JonasTaulien commented on src/Base/StringUtilityInterface.php
> +    public function substring($string, $after, $before);
Ich kann mir vorstellen, dass der Name 'substringBetween' es einfacher machen würde, code zu lesen, der diese Funktion beinhaltet. Was hältst du davon? 
Außerdem hatte ich beim durchlesen des Codes dazu noch ein paar Probleme mit den Variablen-Namen '$after' und '$before'. Von der Reihenfolge in der Parameterliste stehen die Variablen ja vollkommen richtig. Mein Hirn hat ein paar Probleme damit, dass die Varaiable 'after' vor der variable 'before' steht und anders herum. Fallen dir vielleicht noch alternative Name ein, die noch besser beschreiben, wofür die Werte in den Variablen stehen?

2017-02-02 15:08 UTC, JonasTaulien commented on src/Base/StringUtilityInterface.php
> +     * substring('there is no foo without a bar', 'foobar ', 'baz') === 'there is no foo without a bar'<br />
Ich finde es toll, dass du dich an das von mir benutzte Schema gehalten und Beispiele hinzugefügt hast. Magst du vielleicht noch für folgende Fälle ein Beispiel hinzufügen:
- Einer der beiden Variablen $after und $before ist der leere String
- Beide sind die leeren Strings
- Der Wert aus $after befindet sich hinter dem Wert von $before

2017-02-02 15:08 UTC, JonasRudolph commented on tests/Base/StringUtilityInterfaceTest.php
> +    public function substringDataProvider()
Den Stil finde ich super! Das sollte ich für die anderen Testdaten auch machen!

2017-02-02 15:08 UTC, JonasRudolph commented on tests/Base/StringUtilityInterfaceTest.php
> +            ]
Magst du hier noch Testdaten für folgende Fälle hinzufügen:
- $after ist der leere String, $before in $string enthalten
- $before ist der leere String, $after in $string enthalten
- $after = $before = ''
- $after befindet sich hinter $before

2017-02-02 15:12 UTC, JonasRudolph commented
Achso: Wäre es möglich, dass du in die README.md noch ein Beispiel für die hinzugefügte Funktion einfügst?

2017-02-03 11:27 UTC, stevleibelt commented on src/Base/StringUtilityInterface.php
> +     * substring('there is no foo without a bar', 'foobar ', 'baz') === 'there is no foo without a bar'<br />
Hi Jonas,

sehr gern. Ich werde dir die Beispiele nachliefern.

2017-02-03 11:32 UTC, stevleibelt commented on src/Base/StringUtilityInterface.php
> +    public function substring($string, $after, $before);
Ich finde den Namen "substringBetween" passender, da es schon ein "substringBefore" und ein "substringAfter" gibt. Ich werde dir ein entsprechenden Pull-Request zukommen lassen :-).

Mit den Variablennamen "$after" und "$before" bin ich auch sehr unzufrieden. Nach langem probieren waren beide Namen dann das "geringste Uebel".
Gerade sind mir "$startAfter" und "$untilBefore" eingefallen. Die Woerter "Zeichen", "Marker", "Limiter", "Delimiter" schwirren auch noch in meinem Kopf rum, ergeben aber noch keine Bezeichnung mit der ich zufrieden bin.
Es ist in der Tat schwer zu fassen, da die uebergebenen Zeichenketten nicht im Substring enthalten sind (was bei meinen Fallbeispielen aber immer gewuenscht ist).

2017-02-03 11:32 UTC, stevleibelt commented on tests/Base/StringUtilityInterfaceTest.php
> +            ]
Das mache ich sehr gern. Ich denke das ich alle Aenderungen in einem Pull-Request packen werde.

2017-02-03 12:12 UTC, JonasRudolph commented on src/Base/StringUtilityInterface.php
> +     * substring('there is no foo without a bar', 'foobar ', 'baz') === 'there is no foo without a bar'<br />
Super :)

2017-02-03 12:13 UTC, JonasRudolph commented on src/Base/StringUtilityInterface.php
> +    public function substring($string, $after, $before);
Cool, dass wir beide den Namen besser finden :) 
Die Variablennamen "$startAfter" und "$untilBefore" finde ich gut!

2017-02-03 12:14 UTC, JonasRudolph commented on tests/Base/StringUtilityInterfaceTest.php
> +            ]
Vielen dank! Ja, das ist eine sehr gute Idee!

2017-02-03 20:49 UTC, stevleibelt commented on tests/Base/StringUtilityInterfaceTest.php
> +    public function substringDataProvider()
:-)))) - open source baby 👍

2017-02-03 20:52 UTC, closed without merging